dzikoysk/reposilite

reposilite-backend/src/main/java/org/panda_lang/reposilite/ReposiliteLauncher.java
Hello there,
first of all I'd wish to thank you for this project, I've been using it a lot lately for my projects and it's a great piece of software.
I'm using the Docker-based version on a K8S environment and I recently upgraded the docker image and noticed that it was no longer working, I think I might have found the issue, which is that the you probably forgot to run the Future.
It looks like it's working now on my side with this simple fix.
Would it be possible for you to merge this fix (or provide an equivalent fix if you have a better idea)?
Thanks a lot!
=> Reposilite is not starting up

reposilite-frontend/src/views/Dashboard.vue
Something my IDE caught.  
Feel free to close this PR and fix in your own commit if you want, I realize this is a very small PR. 😅 
I just didn't want to include it in a non-related PR.
=> Small typo

reposilite-frontend/src/views/Index.vue, reposilite-frontend/src/views/dashboard/Index.vue
Continuing from #186, this adds navigation to the dashboard.
I know you mentioned a Pug formatting issue, if you want to let me know I can fix it in both spots for this PR since this will likely have the same issue. 🙂
=> Dashboard qualifier navigation

reposilite-backend/pom.xml, reposilite-backend/src/test/groovy/org/panda_lang/reposilite/auth/AuthControllerTest.groovy, reposilite-backend/src/test/groovy/org/panda_lang/reposilite/repository/LookupApiControllerTest.groovy
=> GH-274 Bump CDN to 1.5.1 and adapt changes

reposilite-backend/src/main/java/org/panda_lang/reposilite/console/CliController.java
=> GH-434 Add a separator between alias and address in CLI

reposilite-backend/README.md, reposilite-backend/src/main/kotlin/com/reposilite/config/Configuration.kt, reposilite-backend/src/test/workspace/reposilite.cdn
Following up on #713, I've changed the default host config. Also went over some minor spelling errors I encountered when studying the docs today.
=> GH-713 Make 0.0.0.0 default hostname and fix typos

reposilite-frontend/src/components/header/LoginModal.vue
=> GH-670 Fix displaying of object instead of error message in auth form

reposilite-frontend/src/components/browser/Browser.vue
=> GH-672 Add bottom margin to Browser

reposilite-frontend/package.json, reposilite-frontend/src/components/browser/Card.vue, reposilite-frontend/src/components/icons/CopyIcon.vue
=> GH-676 Add copy button to snippets

Dockerfile
=> GH-725 Copying shadowJar result in Dockerfile.

reposilite-frontend/src/components/browser/Browser.vue
=> GH-669 Add interactive breadcrumbs

reposilite-frontend/src/components/browser/Card.vue
=> GH-668 Reimplement card

reposilite-backend/src/main/kotlin/com/reposilite/token/RouteCommands.kt, reposilite-site/docs/authorization.md, reposilite-site/docs/install.md
Also minor token-related clarity fixes.
=> GH-557 Mention temporary tokens in the docs

reposilite-site/website/sidebars.json
I forgot to update the sidebar in my first PR oops!
=> GH-557 Fix sidebar

.github/README.md, reposilite-site/docs/about.md
Only minor changes to fix some typos. I'm no native speaker so they could also be wrong. 
I have no idea why the "about.md" line 24 was changed.
=> fixed some typos

reposilite-site/docs/faq.md
Added two missing `<br>` tags for line break.
=> GH-557 Add line breaks to fit other Q/A format

reposilite-backend/src/main/kotlin/com/reposilite/frontend/FrontendFacade.kt
=> GH-1416 Fix frontend settings reload

entrypoint.sh
c.f https://github.com/dzikoysk/reposilite/issues/1437
=> GH-1437 Check presence of working directory parameter in REPOSILITE_OPTS (Fix #1437)

reposilite-frontend/src/components/card/CardMenu.vue, reposilite-frontend/src/components/card/CodeSnippet.vue
Fixes the CardMenu dropdown selection, previously it tried to use a method that didn't exist and would just throw errors.
=> GH-1459 Fix CardMenu dropdown selection 

reposilite-site/data/guides/installation/docker.md
Reposilite binds to port 8080 by default, not 80
=> Fix Docker commands

reposilite-backend/src/main/kotlin/com/reposilite/console/infrastructure/ConsoleWebSocketHandler.kt
I caught the error and added the debug logging as asked for in issue #1604. please check if the logging was done correctly
=> GH-1604 Mute subscriber that tries to write to closed output

reposilite-site/pages/plugin/[id].js
=> GH-1603 Fix plugin version dropdown color in dark theme

reposilite-frontend/src/components/card/XmlTag.vue
Fix #1619, since this is 1 character change, please mark this pull request with an "invalid" label to stop it from being counted towards Hacktoberfest.
=> GH-1619 Fix XML tag bracket formatting

reposilite-site/pages/guide/[id].js
Fixes the grammar on the bottom of each page.
=> GH-1731 Fix Grammar

reposilite-backend/src/main/resources/tinylog.properties
Fixes https://github.com/dzikoysk/reposilite/issues/1730
Also makes sure rotation happens at least once per month.
=> GH-1730 Compress archived logs by default, rotate monthly

reposilite-backend/src/main/kotlin/com/reposilite/web/HttpServer.kt, reposilite-backend/src/main/kotlin/com/reposilite/web/api/HttpServerEvents.kt, reposilite-backend/src/main/kotlin/com/reposilite/web/application/JavalinConfiguration.kt
=> Add Event suffix to HttpServerStarted event name

reposilite-site/data/guides/guides.js, reposilite-site/data/guides/migration/nexus-3.md
I used these steps to migrate Nexus 3 repository.
=> Nexus 3 migration guide

reposilite-site/data/guides/guides.js, reposilite-site/data/guides/integrations/nixos.md
I am by no means expert on NixOS, but I created these scripts to install Reposilite on NixOS.
=> NixOS installation guide

reposilite-site/data/guides/authentication/routes.md
Updated the documentation to find information about multiple permissions per route.
=> updated route authentication documentation

reposilite-backend/src/main/kotlin/com/reposilite/maven/MirrorService.kt
=> GH-1827 fix: toString instead of .name

reposilite-backend/src/main/kotlin/com/reposilite/console/application/ConsolePlugin.kt
Add message 
> Startup Done! For help, type "help" or "?"
After reposilite is up and running.
=> Add StartupDone message!

entrypoint.sh
The current nightly isn't start, cause of some bash script problems. This pr fixes them
=> Fix reposilite not starting using docker

reposilite-site/data/guides/integrations/apache.md
I improved the apache guide, so e.g. a different base path and SSL is documented.
resolves #1939
=> GH-1939 Improve Apache guide

reposilite-frontend/src/store/session.js
Resolve #1953
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find?retiredLocale=pl
before:
after:
=> GH-1953 Fix validation permission for path.

.run/Run Reposilite - Test workspace.run.xml, reposilite-backend/src/main/kotlin/com/reposilite/ReposiliteFactory.kt, reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenEndpoints.kt, reposilite-backend/src/main/kotlin/com/reposilite/redirect/RedirectPlugin.kt, reposilite-backend/src/main/kotlin/com/reposilite/web/api/Routing.kt, reposilite-backend/src/main/kotlin/com/reposilite/web/api/RoutingSetupEvent.kt, reposilite-backend/src/main/kotlin/com/reposilite/web/application/JavalinConfiguration.kt, reposilite-backend/src/main/kotlin/com/reposilite/web/infrastructure/ReposiliteRouting.kt, reposilite-backend/src/main/resources/META-INF/services/com.reposilite.plugin.api.ReposilitePlugin
=> GH-2076 Prototype redirect plugin

reposilite-frontend/fake-api/extensions.cjs
=> GH-2143 Fix invalidCredentials response

reposilite-frontend/fake-api/fake-reposilite-backend.js
=> GH-2147 Fix for manager permission

reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenEndpoints.kt, reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenLatestApiEndpoints.kt, reposilite-backend/src/main/kotlin/com/reposilite/shared/extensions/JavalinExtensions.kt, reposilite-backend/src/main/kotlin/com/reposilite/shared/http/HttpRemoteClient.kt, reposilite-backend/src/main/kotlin/com/reposilite/storage/api/FileDetails.kt, reposilite-backend/src/main/kotlin/com/reposilite/storage/filesystem/FileSystemStorageProvider.kt, reposilite-backend/src/main/kotlin/com/reposilite/storage/s3/S3StorageProvider.kt
=> GH-2161 Support Last-Modified header

reposilite-site/data/guides/infrastructure/apache.md
=> GH-2163 Bugfix Apache documentation

reposilite-frontend/index.html
=> GH-2166 Fix load of favicon.png

reposilite-backend/src/main/kotlin/com/reposilite/frontend/FrontendFacade.kt, reposilite-backend/src/main/kotlin/com/reposilite/maven/MavenFacade.kt, reposilite-backend/src/main/kotlin/com/reposilite/maven/RepositoryService.kt, reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/DirectoryIndexPage.kt, reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenEndpoints.kt
=> GH-2176 Display directory index for Ivy

adr/v4/authentication.md, adr/v4/configuration.md, adr/v4/dashboard.md, adr/v4/database.md, adr/v4/repositories.md, adr/v4/ui.md, adr/v4/user-system.md
=> GH-2252 ADR

reposilite-backend/src/main/kotlin/com/reposilite/storage/s3/S3StorageProviderFactory.kt
=> GH-2371 S3StorageProvider - fallback to AWS_REGION

reposilite-backend/build.gradle.kts
=> GH-2374 Support AWS Web Identity Tokens

reposilite-backend/README.md
Document how to also skip integration tests
=> GH-2376 Exclude integrationTest task from the example run command
