dzikoysk/reposilite

- reposilite-backend/src/test/java/org/panda_lang/reposilite/ReposiliteIntegrationTest.java
- reposilite-backend/src/test/java/org/panda_lang/reposilite/ReposiliteLauncherTest.java
- reposilite-backend/src/test/java/org/panda_lang/reposilite/console/CliControllerTest.java
- reposilite-backend/src/test/java/org/panda_lang/reposilite/repository/LookupControllerTest.java
The tests use by default port 80 which raises two issues : it needs root privileges and may be already in use by an existing web server. This patch generates a random port between 49152 and 65534 to run the tests and fix several ones for this new behaviour
There are several ways to fix the original issue : I've chosen to pick a random port on execution but we can also use a fixed port for the tests (as long as it's above 1024). We can also let the user decide on execution by setting a system property.
I hope you'll find this useful.
> GH-132 Change tests to use random high listening port instead of 80

- reposilite-frontend/src/mixins.js
- reposilite-frontend/src/views/Index.vue
I am fairly new to Vue and this is the first time I've looked at Pug, so I'm not sure if there is a better way to achieve this.
This PR allows a user to quickly navigate along the qualifier path.
Ignore no files showing, I was only testing with the frontend and an artificial qualifier. 😅
> Navigation across qualifier path

- reposilite-backend/src/main/java/org/panda_lang/reposilite/ReposiliteHttpServer.java
- reposilite-site/docs/faq.md
Addresses https://github.com/dzikoysk/reposilite/issues/259 by way of system property.
* Only takes effect when debug is enabled
* Defaults to 8MB
* I've updated the FAQ but I wasn't sure how to test the links, I'm not much of a web dev, but I *think* the links should work
> Added system property to set Javalin's requestCacheSize when using debug

- reposilite-backend/src/main/java/org/panda_lang/reposilite/console/Console.java
This fixes this inconsistency on the Dashboard CLI:
> GH-268 Add '?' token for HelpCommand

- reposilite-backend/src/main/java/org/panda_lang/reposilite/repository/DiskQuota.java
- reposilite-backend/src/main/java/org/panda_lang/reposilite/repository/RepositoryStorage.java
- reposilite-backend/src/test/groovy/org/panda_lang/reposilite/repository/RepositoryStorageTest.groovy
Fixes the bug, that the disk quota usage isn't updated correctly when uploading a new file. This is caused by reading the size of the locked file before the new file is written to it.
Adds a test to ensure that the disk quota usage is updated correctly.
> GH-306 Fix disk quota allocation when storing a file

- Dockerfile
This PR fixes artifacts always being returned with `Content-Type: text/plain` when Reposilite is run from the default image, which resulted in Firefox saving all artifacts with the `.txt` file extension (tested with Firefox 82.0.3 on Windows 10 20H2, and reposilite 2.9.6 from the official image on the server).
Reposilite uses [`java.nio.file.Files.probeContentType(Path)`](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/nio/file/Files.html#probeContentType(java.nio.file.Path)) when determining the content type of an artifact, and if this returns `null` then it falls back to Javalin's default of `text/plain`. On Linux, OpenJDK [uses the `/etc/mime.types` file to determine file types](https://github.com/openjdk/jdk/blob/jdk-14+0/src/java.base/unix/classes/sun/nio/fs/MimeType …
> Fix incorrect Content-Type headers in Docker

- reposilite-backend/src/main/java/org/panda_lang/reposilite/Reposilite.java
- reposilite-backend/src/main/java/org/panda_lang/reposilite/repository/DeployService.java
- reposilite-backend/src/test/groovy/org/panda_lang/reposilite/repository/DeployEndpointTest.groovy
- reposilite-backend/src/test/groovy/org/panda_lang/reposilite/repository/DeployServiceTest.groovy
This PR fixes an issue where if you deploy to a rewritten URL it doesn't work, e.g. http://localhost. The deploy does succeed but the files are written to the wrong directory (without the default repository.).
I've tested this and it works fine for us, but obviously, I might have missed something or there might be a better implementation.
> GH-379 Rewrite DeployService URLs

- reposilite-backend/src/main/java/org/panda_lang/reposilite/stats/StatsEntity.java
- reposilite-backend/src/main/java/org/panda_lang/reposilite/stats/StatsService.java
This PR switches to using `ConcurrentHashMap.merge()`  instead of `HashMap.compute()` when collecting statistics.
I was getting this in the logs when I had our internal repo with no proxies defined as the first repository.
Our builds run with blank repositories, meaning all resources are always resolved, so a lot of traffic.
14:19:41.418 ERROR | /releases/org/hibernate/hibernate-validator/5.3.6.Final/hibernate-validator-5.3.6.Final.pom: java.util.ConcurrentModificationException
at java.base/java.util.HashMap.compute(HashMap.java:1229)
at org.panda_lang.reposilite.stats.StatsService.record(StatsService.java:37)
at org.panda_lang.reposilite.ReposiliteHttpServer.lambda$start$0(ReposiliteHttpServer.java:78)
at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:42)
at …
> GH-425 Address ConcurrentModificationException when computing stats.

- reposilite-site/docs/docker.md
Adds documentation for ARM-based Docker image. 
Including example working Dockerfile and how to build it.
Not really sure if this should be PR'd to branch 3.0 or master, but from the comments on the issue i guessed it was for the 3.0
> GH-516 Document ARM-based Docker image

- reposilite-site/docs/reverse-proxy.md
Nginx by default has a max body size of [1MB](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size). This PR aims to notify the reader about the maximum.
> GH-551 Add 'client_max_body_size' nginx option to docs

- reposilite-frontend/src/store/maven/repository.js
Added this to my personal build and thought it could be a good addition for the main release.
When on the overview and selecting a repository, e.g. releases, it adds "-releases" behind the repository id. 
Nothing is added when no repository is selected (unlike the domain, where "{repository}" is added instead. I don't think this would be good here, so I just left it as is).
> GH-458 Added repository name to maven id

- reposilite-frontend/src/components/Console.vue
Closes #745 
To be clear before reading further, this PR **does** focus the input _after_ the transition occurs.  
Below is just an explanation on why I deferred to `setTimeout`.
Please let me know if you are aware of a cleaner solution.
-----
When focusing the console immediately (even using `nextTick`), I ended up with a UI glitch like so
Setting the timeout was the only way I could get the animation to finish before focusing. It's more or less imperceptible, but I tend to dislike "timing" solutions.
I was unable to hook into the events from the tab library used in a way that didn't cause the above glitch, either.
> GH-745 Focus console

- reposilite-frontend/fake-api/extensions.js
- reposilite-frontend/src/store/console/log.js
Fixes #744 
If you look at the screenshot in #744 you'll notice the Java/Kotlin logger only sends a single pipe (`|`).  
This is one solution, another would be to instead insert the required extra pipe in the Java/Kotlin logger (whereas this changes the search to only look for one).
I've also changed the fake API logger to only send a single pipe for closer consistency.
> Fix Filter

- reposilite-backend/src/main/kotlin/com/reposilite/badge/BadgeFacade.kt
- reposilite-backend/src/main/kotlin/com/reposilite/badge/api/LatestBadgeRequest.kt
- reposilite-backend/src/main/kotlin/com/reposilite/badge/infrastructure/BadgeEndpoints.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/MavenFacade.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/MetadataService.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/api/VersionLookupRequest.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/infrastructure/MavenApiEndpoints.kt
- reposilite-backend/src/test/kotlin/com/reposilite/maven/MavenFacadeTest.kt
If you have something that should be implemented differently just write me. It might be also useful to add a filter to show only `alpha`, `beta` or `release` versions, but I think that should be in a second pull request if we want to implement this.
> GH-956 allow versions to be filtered

- .github/README.md
npm install does not require `run`
> Readme: update npm install command

- reposilite-site/docs/deploy.md
Expanded deploy with the following changes:
- Explain how to add multiple repositories (snapshots & releases) for both maven and gradle.
- Explain how to store secrets in global `gradle.properties` file.
- Explain how to use publishing with a gradle kotlin buildscript.
> Expand deploy documentation

- reposilite-backend/src/main/kotlin/com/reposilite/auth/LdapAuthenticator.kt
- reposilite-backend/src/test/kotlin/com/reposilite/auth/LdapAuthenticatorTest.kt
When configuring reposilite against an LDAP server the connector fails to filter users when there is more than one user in the directory. 
The root cause is in the LdapAuthenticator.kt authenticate function. The first directory search filters users based on the auth request name matched to the userAttribute. There is a second directory search after the user is authenticated where only the userFilter is applied, however the authentication request name is not used nor available to that filter.
Adding the userFilter with userAttribute matched with the authentication request name, as done in the first search resolves the error and makes the ldap connector functional against a realistic directory.
> GH-1246 Fix for ldap search filter

- .github/README.md
Links were pointing to old docs url, resolving in 404.
> README : Fix Links to Official Guide

- .github/workflows/publish-snapshot.yml
The axion-release-plugin couldn't get the current version during the docker nightly build because the `.git` folder was not available. With a manual checkout the `.git` folder should be available now.
Previously the generated jar was `reposilite-0.1.0-SNAPSHOT.jar` (that is the default version) and `COPY --from=build /home/reposilite-build/reposilite-backend/build/libs/reposilite-3*.jar reposilite.jar` didn't work.
> GH-1322 Fix docker nightly builds (add .git directory to build context)

- reposilite-backend/build.gradle.kts
- reposilite-backend/src/generated/kotlin/com/reposilite/ReposiliteProperties.kt
- reposilite-backend/src/main/kotlin/com/reposilite/Reposilite.kt
- reposilite-backend/src/main/kotlin/com/reposilite/plugin/api/Plugin.java
- reposilite-backend/src/template/kotlin/com/reposilite/ReposiliteProperties.kt
The contents of `src/template/kotlin` are copied to `src/generated/kotlin` and `@version@` gets replaced with the version.
I think `src/generated/kotlin` is better than `build/generated/kotlin` because otherwise the ide would show an error before the first compilation and after each `./gradlew clean`.
> GH-1330 Internal version for snapshot builds

- reposilite-site/data/plugins/migration.md
While browsing the reposilite website, I noticed that the plugin description for the Migration plugin was copied from the Swagger UI plugin. This is of course not intended, as they do completely different things. This PR aims to fix this issue.
> Fix wrong plugin description

- reposilite-site/data/guides/integrations/nginx.md
Added some notes on what IP address to use when using Nginx as reverse proxy in different scenarios as we previously had some people getting confused about it.
> GH-1397 Explain the IP to use for Nginx reverse proxy

- reposilite-plugins/javadoc-plugin/src/main/kotlin/com/reposilite/plugin/javadoc/JavadocFacade.kt
Adds the ability to use the javadoc-plugin with snapshot versions.
See #1423 for more information
I am not very familiar with the code base so if there is a better way of doing this, please let me know so I can improve.
> GH-1423 Add snapshot support to javadoc-plugin

- reposilite-site/data/guides/features/deployment.md
For `~/m2/settings.xml`, configurations should be placed inside `settings` tag. If it's not there, maven deploy plugin fails in some cases with a misleading error  `401 Unauthorized`.
For reference, please see https://github.com/dzikoysk/reposilite/issues/1455#issuecomment-1175224848
> GH-1455 Guide Improvement. Adding <settings> wrapper for m2 settings

- reposilite-backend/src/main/kotlin/com/reposilite/ReposiliteFactory.kt
- reposilite-backend/src/main/kotlin/com/reposilite/ReposiliteParameters.kt
Since plugins are technically a part of the code, not the configuration, it should be possible to separate them from the workdir.
> GH-1467 Make the plugin directory configurable

- .github/workflows/gradle.yml
- .github/workflows/publish-release.yml
- .github/workflows/publish-snapshot.yml
This pull request aims to improve the GitHub Actions workflows.
To do this, this pull request:
- Updates all Actions to the latest versions.
- Uses the `gradle-build-action` to build with Gradle. (1)
- Adds steps to push Reposilite to GHCR.
- Attempt to improve readability.
1: The [`gradle-build-action`](https://github.com/gradle/gradle-build-action/) has several advantages:
- Easier to use,
- More sophisticated and more efficient caching,
- Detailed reporting of cache usage,
Note: It's kind of hard to test Actions workflows, so I am not sure if this is going to work on
the first attempt. I apologise in advance if this breaks.
> GH-1557 Update and improve Actions workflows

- reposilite-backend/src/main/kotlin/com/reposilite/storage/s3/S3StorageProviderFactory.kt
Fixes #1666 by always setting a region on the S3 client.
I've not been able to test this locally (even with the docker-compose config), and have never written Kotlin, so I am unsure whether this works. If another solution is preferred feel free to close this PR.
> Set default S3 region to prevent crashes

- reposilite-site/data/guides/guides.js
- reposilite-site/data/guides/integrations/caddy.md
I use Caddy as a reverse proxy to reposilite. The amount of configuration needed to run a reverse proxy over HTTPS is spectacularly lower than nginx. This might be of interest to others as well and might fit in many cases.
> GH-1694 Create Caddy guide

- reposilite-backend/src/main/kotlin/com/reposilite/javadocs/JavadocFacade.kt
The /javadoc/ handler /latest logic didn't work because it removed the leading / from the URL when redirecting.
A URL like:
`http://0.0.0.0:8080/javadoc/everything/com/bergerkiller/bukkit/BKCommonLib/latest`
Turnt into:
`http://0.0.0.0:8080/javadoc/everything/com/bergerkiller/bukkit/BKCommonLib1.19.3-SNAPSHOT`
Instead of:
`http://0.0.0.0:8080/javadoc/everything/com/bergerkiller/bukkit/BKCommonLib/1.19.3-SNAPSHOT`
> GH-1692 Fix broken javadoc latest redirect

- reposilite-backend/src/main/kotlin/com/reposilite/storage/Comparators.kt
- reposilite-backend/src/test/kotlin/com/reposilite/shared/fs/FileComparatorsTest.kt
- reposilite-backend/src/test/kotlin/com/reposilite/storage/VersionComparatorTest.kt
- reposilite-backend/src/test/kotlin/com/reposilite/storage/specification/VersionComparatorSpecification.kt
I ran into a problem with javadoc /latest selecting version 1.19-SNAPSHOT over 1.19.3-SNAPSHOT, and after a bit of digging the problem was found to be a simple mistake. I've added a couple unit tests so I could verify that my fix had the intended effect.
One test case was modified to suit this new ordering, I don't know if that is a problem or not. By the rules of the algorithm 1.1 and 1.1.2 (release) should be newer than 1.1-SNAPSHOT, so this causes all words to be sorted to the front instead of the bottom. (might need a re-build as the auto test failed earlier because of it)
> GH-1726 Bugfix for version comparator + tests

- reposilite-backend/src/main/kotlin/com/reposilite/javadocs/JavadocFacade.kt
Some javadoc doclets and taglets produce SVG images. This PR adds support for them.
Tested by publishing a project using one such doclet to an instance of reposilite with this change and verifying that it is displayed correctly.
There is one oddity in the embedded view: links in the SVG do not work, while links outside it do.
This is, however, not an issue in the raw view.
> Add SVG as supported javadoc type

- .github/README.md
- reposilite-site/data/guides/guides.js
- reposilite-site/data/guides/installation/archlinux.md
For a while now there has been an AUR package for reposilite, to aid in the installing on Arch (and arch based distributions).
I have added the basic installation from the AUR (without an AUR helper) however I have also left a link to the Arch Wiki which has a lot of information on the installation process on Arch Linux.
As for me, I am the co-maintainer of the AUR package, and I am the maintainer of the reposilite ArchWiki page, so any issues with it please let me know.
Any issues with the AUR package can be submitted on the repository here: https://onedev.polarian.dev/polarrepo/reposilite
You can also install reposilite directly, already packaged, from PolarRepo (an unofficial arch repository which I maintain to aid in installation of AUR packages I maintain), for more information check …
> GH-1738 Add Arch Linux install instructions

- reposilite-frontend/src/components/card/RepositorySnippet.vue
- reposilite-frontend/src/components/card/SnippetsCard.vue
- reposilite-frontend/src/store/maven/repository.js
- reposilite-frontend/vite.config.js
See #1758. A simple change.
Before:
After:
> GH-1758 Add human-readable names for Gradle snippets

- reposilite-backend/src/main/kotlin/com/reposilite/shared/BadgeGenerator.kt
If no custom color is provided the returned SVG document looks like this:
```xml
<g clip-path="url(#r)">
<rect width="98" height="20" fill="#555"/>
<rect x="98" width="49" height="20" fill="#null"/>
<rect width="147" height="20" fill="url(#s)"/>
</g> 
```
with an fill color of `#null` which makes the background black
Example:
> Fix badges having a black background if no custom color is provided

- reposilite-frontend/src/components/console/ConsoleView.vue
These autocomplete pop-ups are very annoying. They can prevent you from using the `↑` or `↓` keys to switch within the command history.
In my opinion, the command input box is not really a form. It's an interactive command input, which doesn't need any browser-provided autocomplete.
So, here's a quick fix for that: set `autocomplete="off"` and that's it.
> Disable auto complete for consoleInput

- Dockerfile
- entrypoint.sh
The actual root cause was that the shebang/hash-bang line in `entrypoint.sh` was not taken into account. This happened because the ENTRYPOINT didn't open a sub-shell like `["/bin/sh", "-c", "/app/entrypoint.sh"]` (not the missing "-c"). Using a sub-shell would introduce another call tree process to the Docker container runtime and is not necessary.
Instead, `["/app/entrypoint.sh"]` is enough to get Reposilite started through an actual bash, like intended with the shebang line in that script.
Doing so resolves the root check issue and identified another issue with the Docker image where the entrypoint file hadn't reliable execute permissions.
Resolves #1924.
> GH-1925 Fix Docker entrypoint.sh root check

- reposilite-backend/src/main/resources/tinylog.properties
The `writerFile.size` has no effect as I've observed the logs far exceeding the default `100MB` limit.
This changes to use the [documented](https://tinylog.org/v2/configuration/#policies) `size` policy.
> GH-1926 Fix tinylog file size policy

- entrypoint.sh
Fix the error when starting the container for the second time： addgroup: The group `reposilite' already exists.
> GH-1934 Check if user/group already exist in entrypoint.sh

- Dockerfile
Fixed the problem of missing public port configuration, causing Docker UI to be unable to recognize the application service port
> Update Dockerfile Add EXPOSE 8080

- reposilite-frontend/src/components/header/HeaderHero.vue
This makes it so that the organization website link opens in a new tab when clicked, rather than replacing the current tab.
> GH-1982 Make `organizationWebsite` open in new tab

- reposilite-backend/src/main/kotlin/com/reposilite/maven/MirrorService.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/Repository.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/RepositoryFactory.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/application/MavenComponents.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/application/MavenPlugin.kt
- reposilite-backend/src/main/kotlin/com/reposilite/maven/application/MavenSettings.kt
- reposilite-backend/src/test/kotlin/com/reposilite/maven/specification/MavenSpecification.kt
This commit adds an option to define a timeout until no re-fetch of maven-metadata.xml is done.
This gives the possibility to use the local copy until the defined period is over. Especially on connections with "huge" delays this setting improves build times and still has a deprecation mechanism for maven-metadata.xml content.
The default value is 0 seconds (it fetches the file every time).
> Add "no-refetch-timeout" for StoragePolicy.PRIORITIZE_UPSTREAM_METADATA

- reposilite-backend/src/main/kotlin/com/reposilite/maven/MirrorService.kt
The logic was in reverse. The file is valid when it is older than the defined time-range.
This commit reverses the logic and makes the feature usable.
> GH-2042 Fix logic in isMetadataFileValid

- reposilite-site/data/guides/installation/general.md
Fix https://reposilite.com/guide/general "Standalone" link taking you to `/standalone` instead of `/jar` which it should.
> Fix broken link

- reposilite-site/data/guides/installation/docker.md
Added line break char ('\\') to docker run command. Copy pasting the command will now work instead of failing.
> GH-2222 Added line breaks to docker command

- reposilite-plugins/prometheus-plugin/build.gradle.kts
- reposilite-plugins/prometheus-plugin/src/main/kotlin/com/reposilite/plugin/prometheus/PrometheusPlugin.kt
- reposilite-plugins/prometheus-plugin/src/main/kotlin/com/reposilite/plugin/prometheus/metrics/JettyMetrics.kt
- reposilite-plugins/prometheus-plugin/src/main/kotlin/com/reposilite/plugin/prometheus/metrics/ReposiliteMetrics.kt
Hopefully this uncooks the jetty metrics
Also bumps the version for prometheus metrics.
> GH-2251 Fix Jetty Metrics Recording

- reposilite-backend/src/integration/kotlin/com/reposilite/configuration/StartupParametersIntegrationTest.kt
- reposilite-backend/src/main/kotlin/com/reposilite/ReposiliteJournalist.kt
- reposilite-backend/src/main/kotlin/com/reposilite/configuration/ConfigurationUtils.kt
- reposilite-backend/src/main/kotlin/com/reposilite/configuration/shared/infrastructure/LocalSharedConfigurationProvider.kt
- reposilite-backend/src/main/kotlin/com/reposilite/frontend/LazyPlaceholderResolver.kt
- reposilite-backend/src/main/kotlin/com/reposilite/frontend/application/FrontendPlugin.kt
- reposilite-backend/src/main/kotlin/com/reposilite/frontend/infrastructure/FrontendHandler.kt
- reposilite-backend/src/main/kotlin/com/reposilite/javadocs/JavadocContainerService.kt
- reposilite-backend/src/main/kotlin/com/reposilite/javadocs/JavadocFacade.kt
- reposilite-backend/src/main/kotlin/com/reposilite/plugin/PluginLoader.kt
- reposilite-backend/src/main/kotlin/com/reposilite/status/application/StatusPlugin.kt
- reposilite-backend/src/main/kotlin/com/reposilite/storage/Paths.kt
- reposilite-backend/src/main/kotlin/com/reposilite/storage/filesystem/FileSystemQuotaProviders.kt
- reposilite-backend/src/main/kotlin/com/reposilite/storage/filesystem/FileSystemStorageProvider.kt
- reposilite-backend/src/main/kotlin/com/reposilite/storage/filesystem/FileSystemStorageProviderFactory.kt
- reposilite-backend/src/main/kotlin/com/reposilite/token/ExportService.kt
- reposilite-backend/src/test/kotlin/com/reposilite/maven/specification/MavenSpecification.kt
- reposilite-backend/src/test/kotlin/com/reposilite/token/ExportAndImportTest.kt
- reposilite-backend/src/test/kotlin/com/reposilite/token/specification/AccessTokenSpecification.kt
- reposilite-plugins/groovy-plugin/src/main/kotlin/com/reposilite/plugin/groovy/GroovyPlugin.kt
- reposilite-plugins/migration-plugin/src/main/kotlin/com/reposilite/plugin/migration/MigrationPlugin.kt
- reposilite-plugins/migration-plugin/src/test/kotlin/com/reposilite/plugin/migration/MigrationPluginTest.kt
Cleans up a bunch of random little things, but mainly replaces the use of `Files.*` methods over the kotlin extensions to `Path`
Functionally, absolutely nothing should have changed.
> GH-2275 Use file api from kotlin stdlib

- reposilite-site/data/guides/installation/docker.md
Correct the link for "setup#parameters" in https://reposilite.com/guide/docker#reposilite-properties, as it currently directs to `/setup#parameters` instead of the intended `/general#parameters`.
> Fix invalid link to parameters section in Docker guide

- .github/workflows/publish-release.yml
**Purpose**  
This pull request enhances the Docker image tagging process by adding additional tags for `Major` and `Major.Minor` versions alongside the existing `latest` and full release version tags.  
**Why this change?**  
Using only `latest` or the full version (e.g., `3.5.19`) for Docker tags can make managing updates more challenging, especially for users who want to restrict updates to specific major or minor versions. For example:
- A tag like `3.5` allows users to get updates within the `3.5.x` series while avoiding potential changes in version `3.6` without explicit changing the tag.
- Similarly, a `3` tag ensures updates only within the `3.x` series to avoid auto updates with breaking changes.
Adding these tags provides users with more flexibility and control over updates in …
> GH-2282 Add Docker tags for Major and Major.Minor versions

- build.gradle.kts
Change build.gradle.kts, replacing the `kotlinOptions` DSL syntax with the currently supported equivalent `compilerOptions`.
This resolves #2286
> GH-2286 Remove the deprecated `kotlinOptions` DSL

- reposilite-plugins/prometheus-plugin/src/main/kotlin/com/reposilite/plugin/prometheus/metrics/JettyMetrics.kt
- reposilite-plugins/prometheus-plugin/src/main/kotlin/com/reposilite/plugin/prometheus/metrics/QueuedThreadPoolMetrics.kt
- reposilite-plugins/prometheus-plugin/src/main/kotlin/com/reposilite/plugin/prometheus/metrics/ReposiliteMetrics.kt
- reposilite-plugins/prometheus-plugin/src/test/kotlin/com/reposilite/plugin/prometheus/metrics/JettyMetricsTest.kt
- reposilite-plugins/prometheus-plugin/src/test/kotlin/com/reposilite/plugin/prometheus/metrics/QueuedThreadPoolMetricsTest.kt
- reposilite-plugins/prometheus-plugin/src/test/kotlin/com/reposilite/plugin/prometheus/specification/PrometheusPluginSpecification.kt
Fixes #2277 
Should we reset the `StatisticsHandler` when one of its fields is `NaN`?
TODO: add test case for all edge cases of `StatisticsHandler` return values (some things use `Int`, some use `Long`, and some use `Double`):
- `0`
- `Int.MAX_VALUE`
- `Int.MIN_VALUE`
- `Long.MAX_VALUE`
- `Long.MIN_VALUE`
- `Double.MAX_VALUE`
- `Double.MIN_VALUE`
- `Double.NaN`
- `Double.POSITIVE_INFINITY`
- `Double.NEGATIVE_INFINITY`
> Fix Failure When `StatisticsHandler` Returns `NaN`

- .dockerignore
- Dockerfile
- entrypoint.sh
[As per discussed in #2289](https://github.com/dzikoysk/reposilite/pull/2289#issuecomment-2508117580)
- Update entrypoint.sh to be POSIX compatible (formerly used some BASH only syntax) for eventual switch to an Alpine Image.
- Update entrypoint.sh to include a warning about backwards compatibility and the changes coming to docker images with 3.6.X. Script will automatically change permissions of directories that require update.
- Use `eclipse-temurin:21-XXX-noble` images for build and run stages of Dockerfile.
- Speed up build time for local builds of Reposilite images by
- Changing the ordering of Dockerfile instructions to allow for more parallel building and increased cache hits
- Include an .dockerignore file to exclude most non-application files.
> GH-2288 Migrate Docker images to Ubuntu and Eclipse Temurin and change user/group id

- reposilite-site/data/guides/features/javadocs.md
I added the missing <repository> part to example javadoc path.
> GH-2420 Add repository to javadoc example path in docs

- reposilite-site/data/guides/migration/artifactory.md
* broken in 813c6f6c9cce8945471c76a2805f41ff60085fd1
* file renamed from settings to general
* commit directs the hyperlink to the new page location
> docs: fix hyperlink that broke with commit
